jobs:
  check-a:
    needs:
    - fast-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - uses: hustcer/setup-nu@v3
      with:
        check-latest: true
    - name: report
      run: nu ./report.nu artifacts/results/result_parsed.json check-a
    timeout-minutes: 60
  check-b:
    needs:
    - fast-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - uses: hustcer/setup-nu@v3
      with:
        check-latest: true
    - name: report
      run: nu ./report.nu artifacts/results/result_parsed.json check-b
    timeout-minutes: 60
  check-c:
    needs:
    - fast-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - uses: hustcer/setup-nu@v3
      with:
        check-latest: true
    - name: report
      run: nu ./report.nu artifacts/results/result_parsed.json check-c
    timeout-minutes: 60
  fast-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: determinatesystems/nix-installer-action@main
      with:
        determinate: false
        diagnostic-endpoint: ''
        logger: pretty
        source-url: https://install.lix.systems/lix/lix-installer-x86_64-linux
    - name: nix-fast-build
      run: nix run nixpkgs#lixPackageSets.latest.nix-fast-build -- --no-nom --flake
        ".#checks.x86_64-linux" --result-file result.json || true
    - name: transform
      run: nix shell nixpkgs#unixtools.script nixpkgs#nushell --command nu ./transform.nu
        result.json
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: './result_parsed.json

          ./result-*

          '
    timeout-minutes: 60
  pre-commit:
    needs:
    - fast-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - uses: hustcer/setup-nu@v3
      with:
        check-latest: true
    - name: report
      run: nu ./report.nu artifacts/results/result_parsed.json pre-commit
    timeout-minutes: 60
name: Nix x86_64-linux
'on':
  push: {}
  workflow_dispatch: {}
