jobs:
  fast-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        diagnostic-endpoint: ''
        logger: pretty
        source-url: https://install.lix.systems/lix/lix-installer-${{ fromJSON('{"X64":"x86_64","X86":"i686","ARM64":"aarch64","ARM":"armv7l"}')[runner.arch]
          }}-${{ fromJSON('{"Linux":"linux","macOS":"darwin","Windows":"windows"}')[runner.os]
          }}
    - name: nix-fast-build
      run: nix run nixpkgs#lixPackageSets.latest.nix-fast-build -- --no-nom --result-file
        result.json || true
    - name: transform
      run: nix shell nixpkgs#expect nixpkgs#nushell --command nu -- ./transform.nu
        result.json
    - name: cat
      run: cat result.json
    timeout-minutes: 60
'on':
  push: {}
  workflow_dispatch: {}
